<?php
return array(
	'parity' => array(
		'cartCheckoutGating' => 'removed',
		'onCartClickBehaviour' => 'open_drawer',
		'blocksSyncDebug' => false,
	),
	'composite' => array(
		'groupMode' => 'flat',
		'showChildren' => true,
	),
	'ui' => array(
		'showViewCartButton' => true,
		'showCheckoutButton' => true,
		'showItemRemove' => true,
		'showItemQuantity' => true,
		'enableQuantityEditing' => true,
		'showItemLinks' => true,
		'showItemPrice' => true,
		'showItemThumbnail' => true,
		'showSubtotal' => true,
		'showShipping' => true,
		'showTaxes' => true,
		'showTotal' => true,
		'showCoupons' => true,
		'showFloatingCartIcon' => true,
		'lockPageScroll' => true,
		'hideCountWhenZero' => false,
		'openTriggerElementId' => '',
		'badgeElementId' => '',
		'autoOpenOnAddToCart' => true,
	),
	'cssClasses' => array(
		'panel' => '',
		'backdrop' => '',
		'container' => '',
		'header' => '',
		'form' => '',
		'items' => '',
		'item' => '',
		'itemOdd' => '',
		'itemEven' => '',
		'footer' => '',
		'totals' => '',
		'coupon' => '',
		'couponToggle' => '',
		'couponForm' => '',
		'couponInput' => '',
		'couponApplyButton' => '',
		'couponList' => '',
		'couponRemoveButton' => '',
		'floatingIcon' => '',
	),
	'hooksHtml' => array(
		'aboveItems' => '',
		'afterFirstItem' => '',
		'afterActions' => '',
	),
);
