<?php
return array(
	'parity' => array(
		'cartCheckoutGating' => 'removed',
		'onCartClickBehaviour' => 'open_drawer',
		'blocksSyncDebug' => false,
	),
	'composite' => array(
		'groupMode' => 'flat',
		'showChildren' => true,
	),
	'ui' => array(
		'showViewCartButton' => true,
		'showCheckoutButton' => true,
		'showItemRemove' => true,
		'showItemQuantity' => true,
		'enableQuantityEditing' => true,
		'showItemLinks' => true,
		'showItemPrice' => true,
		'showItemThumbnail' => true,
		'showSubtotal' => true,
		'showShipping' => true,
		'showTaxes' => true,
		'showTotal' => true,
		'showCoupons' => true,
		'showFloatingCartIcon' => true,
		'lockPageScroll' => true,
		'hideCountWhenZero' => false,
		'openTriggerElementId' => '',
		'badgeElementId' => '',
		'autoOpenOnAddToCart' => true,
	),
	// Shipping progress bar: threshold in major currency units (0 = disabled).
	// textPending/textReached accept sanitized HTML; the [data-wcsc-amount] element
	// receives the remaining amount formatted for the store currency.
	'shippingProgress' => array(
		'enabled'     => false,
		'threshold'   => 0,
		'textPending' => 'Ti mancano <strong data-wcsc-amount></strong> per la spedizione gratuita!',
		'textReached' => '<strong>Spedizione gratuita sbloccata!</strong>',
	),
	'cssClasses' => array(
		'panel' => '',
		'backdrop' => '',
		'container' => '',
		'header' => '',
		'form' => '',
		'items' => '',
		'item' => '',
		'itemOdd' => '',
		'itemEven' => '',
		'footer' => '',
		'totals' => '',
		'coupon' => '',
		'couponToggle' => '',
		'couponForm' => '',
		'couponInput' => '',
		'couponApplyButton' => '',
		'couponList' => '',
		'couponRemoveButton' => '',
		'floatingIcon' => '',
	),
	'hooksHtml' => array(
		'aboveItems' => '',
		'afterFirstItem' => '',
		'afterActions' => '',
	),
);
